### PR TITLE
Added reading default hi-res image from at2x attributte

### LINKED ISSUE #26: Add support for digest/hash on asset URLs
I would be good to have a mechanism that will support assets generated with hash. What I have in mind is solution similar to the angularjs library (https://github.com/imulus/retinajs#ruby-on-rails-3x) - additional parameter for a retina image url.

### PR DESCRIPTION
**Pull request by przemeq84**
Resolves #26

### CODE REVIEW

**Comment by faceleg** [comment]
@przemeq84 please update the README, pull the latest commits from master, and re-run tests. If all green I will merge

**Comment by przemeq84** [comment]
@faceleg I updated the README and pulled the latest changes. However it seems that tests on travis are run against the minified version so I had to commit also the `/build` directory to make them pass.

I think it may be worth to change the `pre-commit` git hook to run the same tests as travis (`test-min` instead of `test`). This would help in future to avoid committing the code that passes tests locally (using `lib/angular-retina.js`) and fails on travis (using `build/angular-retina.min.js`).

**Comment by faceleg** [comment]
Good call I'll make it run both

**Comment by faceleg** [comment]
Thank you! :dancer:

**Pull request merged**
