### PR TITLE
Allow older angular support for bower

### PR DESCRIPTION
**Pull request by thiagofesta**
Add back support to angular 1.2.x on bower.json
I forced 1.2.28 and ran all tests, seems working fine.

I also fixed the version bump. right now it is 0.3.2, but the tag one is broken. Check this out: https://github.com/jrief/angular-retina/blob/v0.3.2/bower.json

### CODE REVIEW

**Comment by faceleg** [comment]
Please let me or @jrief bump the versions, we'll do it once the PR is accepted

**Comment by faceleg** [comment]
@thiagofesta also, I've commited a fix for the travis build on master, if you would update your copy to contain that fix so we can see the CI build apss for this PR?

**Comment by thiagofesta** [comment]
@faceleg fixed

**Comment by faceleg** [comment]
Thanks!

**Pull request merged**
