### PR TITLE
Add support for URL query parameters. Fixes #40.

### LINKED ISSUE #40: No support for URIs with query paramters after file extension
I have investigated why your directive does not work on my project. I found out that you always check if the image URI ends with one of the supported file extensions. But in my case, the images are delivered from an amazon storage server with a lot of queries at the end of the URI: https://domain.com/hash/fileName.jpg?X-Amz-Algorithm=xxx&X-Amz-Credential=xxx&X-Amz-Date=xxx... So your Regex do not match.

`allowedImageTypesRegex = /(png|jp[e]?g)$/`

`imageUrl.match(allowedImageTypesRegex)
// returns null`

Is it possible to change the regular expression to check not just the end of the URI?

### PR DESCRIPTION
**Pull request by nmalancea**

### CODE REVIEW

**Comment by faceleg** [comment]
Any idea why the build is failing?

**Comment by nmalancea** [comment]
@faceleg No idea at this point. At first I was able to replicate the failing test by downgrading to the Node version used remotely (0.12.18) but even on that version both of my last 2 commits test fine locally. I don't know what else to try. Feel free to close this PR but I'd appreciate it if you try to run it on your machine to see if it succeeds. You can try it without my last commit too.

**Comment by faceleg** [comment]
Tests work on my machine, thanks

**Comment by faceleg** [comment]
Also thanks for trying to get the build going - no idea why it's failing

**Pull request merged**
