### PR TITLE
Feature/example

### PR DESCRIPTION
**Pull request by faceleg**

### CODE REVIEW

**Comment by faceleg** [comment]
Great if we could make this a gh-pages site so people can try this excellent directive out easily

**Comment by jrief** [comment]
I really would appreciate a gh-page for that project. If possible I'd prefer Gulp over Grunt to build/test/deploy the project. My latest angular project (http://jrief.github.io/angular-bootstrap-plus/) uses Gulp to deploy to gh-pages.

**Comment by faceleg** [comment]
I'll copy the bootstrap-plus gh pages portion for now. This will leave us with grunt and gulp for a time, until I manage to convert over the remaining grunt tasks to gulp.

**Comment by faceleg** [comment]
Can you please add a label "beginners", so I can indicate to users which issues are suitable for newcomers to tackle?

**Pull request merged**
